version: '3.8'

services:
  web:
    build:
      context: .
      args:
        DATABASE_URL: postgres://postgres:password@db:5432/product_db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/product_db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
